# Generated by Django 2.2.6 on 2019-10-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mane',
            new_name='name',
        ),
    ]
